# Generated by Django 2.1.5 on 2019-02-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190201_2049'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='products.Product'),
        ),
    ]
